### ISSUE TITLE
Anchor Tag Helpers in navbar-link?

### ISSUE THREAD

**Issue by montyclt** [brecons/bootstrap-tag-helper#29]
There are any plan to implements built-in anchor tag helpers in `<navbar-link>`

Example for razor pages:
`<navbar-link asp-page="/">Index</navbar-link>`

Example for MVC:
`<navbar-link asp-controller="Home" asp-action="Index">Index</navbar-link>`

Regards

**Comment by brecons** [comment]
We are happy to include this in our Release Planning. Thank you for feedback.

**Comment by montyclt** [comment]
Thank you!
