### ISSUE TITLE
Progress height applied to wrong tag

### ISSUE THREAD

**Issue by williamsp2** [brecons/bootstrap-tag-helper#34]
The height style is incorrectly applied to the inner div (.progress-bar) rather than the outer div (.progress).

**Comment by brecons** [comment]
Hi williamsp2! Can you clarify the problem with an example?

**Comment by williamsp2** [comment]
Per bootstrap’s documentation at https://getbootstrap.com/docs/4.1/components/progress/#height<https://getbootstrap.com/docs/4.1/components/progress/%23height>:

<div class="progress" style="height: 1px;">
  <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div>
<div class="progress" style="height: 20px;">
  <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div>

It shows the height style should be applied to the div that has the .progress css class rather than the div that has the .progress-bar css class.  I made the change to a local copy of your project and it fixed the display issue in your test project.

--Patrick

**Comment by brecons** [comment]
Fixed with Pull Request #36
