### ISSUE TITLE
New log for Tag Helper

### ISSUE THREAD

**Issue by reallinfo** [brecons/bootstrap-tag-helper#4]
I wanted to contribute to Tag Helper. I designed a logo for it. If you like it, I'll send you files and pr. 

Please tell me in particular if you have something you want.

![taghelper](https://user-images.githubusercontent.com/36298335/38505190-41d836f6-3c1f-11e8-9327-3b8b8f62c274.jpg)

**Comment by brecons** [comment]
Thanks for your offer. I'll be back soon.
